package classes;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Scanner;

public class ProgramUser {
    public static void main(String[] args) throws StudentNotFoundException, NoStudentsException {
    	Scanner keyboard = new Scanner(System.in);
    	
    	System.out.println("What is the teacher's name?");
    	String name= keyboard.nextLine();
    	System.out.println("What is the teacher's subject");
    	String subject= keyboard.nextLine();	
        Teacher teacher= new Teacher(name, subject);
        boolean exit = false;

        while (!exit) {
            // Main menu options
            System.out.println("\nSelect an option:");
            System.out.println("1. Teacher View");
            System.out.println("2. Student View");
            System.out.println("3. Exit");
            int choice = keyboard.nextInt();
            keyboard.nextLine(); // flush buffer

            switch (choice) {
                case 1:
                    // Teacher login
                    boolean teacherLoggedIn = false;
                    int attempts = 0;
                    while (attempts < 3 && !teacherLoggedIn) {
                        System.out.println("Enter Teacher View password:");
                        String teacherPassword = keyboard.nextLine();
                        if (teacherPassword.equals(teacher.getPassword())) {
                            teacherLoggedIn = true;
                        } else {
                            attempts++;
                            System.out.println("Incorrect password. You have " + (3 - attempts) + " attempts remaining.");
                        }
                    }
                    
                    // If login successful, show teacher view
                    if (teacherLoggedIn) {
                        teacherView(keyboard, teacher);
                    } else {
                        System.out.println("Too many incorrect attempts. Returning to main menu.");
                    }
                    break;
                case 2:
                    // Student view - can be expanded later
                    studentView(keyboard);
                    break;
                case 3:
                    exit = true;
                    break;
                default:
                    System.out.println("Invalid choice. Please try again.");
            }
        }

        keyboard.close();
    }

    // Teacher view methods
    public static void teacherView(Scanner keyboard, Teacher teacher) {
        boolean exitTeacherView = false;
        while (!exitTeacherView) {
            System.out.println("\nTeacher View:");
            System.out.println("1. Add Student");
            System.out.println("2. Display All Students");
            System.out.println("3. Return to Main Menu");
            int choice = keyboard.nextInt();
            keyboard.nextLine(); // clear buffer

            switch (choice) {
                case 1:
                    addStudent(keyboard, teacher); // Add a new student
                    break;
                case 2:
                    teacher.getClassList(); // Show all students
                    break;
                case 3:
                    exitTeacherView = true; // Exit to main menu
                    break;
                default:
                    System.out.println("Invalid choice. Please try again.");
            }
        }
    }

    // Add a new student with an autogenerated ID and password
    public static void addStudent(Scanner keyboard, Teacher teacher) {
        System.out.println("Enter the first name of the new student:");
        String firstName = keyboard.nextLine();
        System.out.println("Enter the last name of the new student:");
        String lastName = keyboard.nextLine();

        // Generate unique ID for the student
        String studentId = "student" + (teacher.getStudents().size() + 1);
        String password = studentId; // ID as password

        Student newStudent = new Student(firstName, lastName, studentId, password);
        teacher.addStudent(newStudent);

        System.out.println("Student added with ID: " + studentId + " and password: " + password);
    }

    // Student view (could be expanded with more functionality)
    public static void studentView(Scanner keyboard) {
        System.out.println("Student view: (not yet implemented)");
        // Placeholder for student view functionality
    }
}